-- Travel Guide PostgreSQL schema (Supabase/PostgreSQL 15+).
-- Safe to run repeatedly. It creates objects but never drops or truncates data.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'scout', 'user')),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    profile_picture TEXT,
    remember_token VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON users (LOWER(email));
CREATE INDEX IF NOT EXISTS users_role_verified_idx ON users (role, is_verified);

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scout_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    short_history TEXT NOT NULL,
    country VARCHAR(100) NOT NULL,
    genre VARCHAR(50) NOT NULL,
    cost_level VARCHAR(20) NOT NULL CHECK (cost_level IN ('low', 'medium', 'high')),
    travel_medium_info TEXT NOT NULL,
    image_paths JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS posts_status_created_idx ON posts (status, created_at DESC);
CREATE INDEX IF NOT EXISTS posts_scout_status_idx ON posts (scout_id, status);
CREATE INDEX IF NOT EXISTS posts_country_idx ON posts (country);

CREATE TABLE IF NOT EXISTS post_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scout_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_data JSONB NOT NULL,
    original_post_id BIGINT REFERENCES posts(id) ON DELETE SET NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    reject_reason VARCHAR(255)
);

CREATE INDEX IF NOT EXISTS post_requests_scout_status_idx ON post_requests (scout_id, status);
CREATE INDEX IF NOT EXISTS post_requests_pending_idx ON post_requests (requested_at) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS wishlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT wishlist_user_post_unique UNIQUE (user_id, post_id)
);

CREATE INDEX IF NOT EXISTS wishlist_user_added_idx ON wishlist (user_id, added_at DESC);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 1000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS comments_post_created_idx ON comments (post_id, created_at DESC);

CREATE TABLE IF NOT EXISTS cost_estimates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL UNIQUE REFERENCES posts(id) ON DELETE CASCADE,
    base_cost NUMERIC(10, 2) NOT NULL CHECK (base_cost >= 0),
    currency VARCHAR(10) NOT NULL DEFAULT 'USD',
    last_updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Block Supabase anon/authenticated Data API access. The Render app connects directly to PostgreSQL.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishlist ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_estimates ENABLE ROW LEVEL SECURITY;
