display_errors=Off
display_startup_errors=Off
log_errors=On
error_reporting=E_ALL
expose_php=Off
upload_max_filesize=2M
post_max_size=12M
max_file_uploads=5
session.use_strict_mode=1
session.cookie_httponly=1
session.cookie_samesite=Lax
date.timezone=UTC
