<?php
return [
    'GET' => [
        '/' => ['HomeController', 'index'],
        '/login' => ['AuthController', 'showLogin'],
        '/register' => ['AuthController', 'showRegister'],
        '/logout' => ['AuthController', 'logout'],
        '/profile' => ['ProfileController', 'show'],
        '/wishlist' => ['WishlistController', 'index'],
        '/scout/requests' => ['ScoutController', 'requests'],
        '/scout/request/create' => ['ScoutController', 'createForm'],
        '/scout/request/edit' => ['ScoutController', 'editForm'],
        '/scout/approved' => ['ScoutController', 'approved'],
        '/scout/change-request' => ['ScoutController', 'changeForm'],
        '/admin' => ['AdminController', 'dashboard'],
        '/admin/users' => ['AdminController', 'users'],
        '/admin/users/add' => ['AdminController', 'addUserForm'],
        '/admin/posts' => ['AdminController', 'posts'],
        '/admin/posts/edit' => ['AdminController', 'editPostForm'],
        '/admin/comments' => ['AdminController', 'comments'],
        '/posts' => ['PostController', 'index'],
        '/posts/detail' => ['PostController', 'detail'],
    ],
    'POST' => [
        '/login' => ['AuthController', 'login'],
        '/register' => ['AuthController', 'register'],
        '/profile' => ['ProfileController', 'update'],
        '/scout/request/create' => ['ScoutController', 'store'],
        '/scout/request/edit' => ['ScoutController', 'update'],
        '/scout/change-request' => ['ScoutController', 'store'],
        '/admin/users/add' => ['AdminController', 'addUser'],
        '/admin/posts/edit' => ['AdminController', 'updatePost'],
        '/api/wishlist/add' => ['WishlistApiController', 'add'],
        '/api/wishlist/remove' => ['WishlistApiController', 'remove'],
        '/api/scout/request/delete' => ['ScoutApiController', 'delete'],
        '/api/admin/verify' => ['AdminApiController', 'toggleVerify'],
        '/api/admin/request/approve' => ['AdminApiController', 'approveRequest'],
        '/api/admin/request/reject' => ['AdminApiController', 'rejectRequest'],
        '/api/admin/post/delete' => ['AdminApiController', 'deletePost'],
        '/api/admin/comment/delete' => ['AdminApiController', 'deleteComment'],
        '/api/comments/add' => ['CommentApiController', 'add'],
    ],
    'DELETE' => [
        '/api/wishlist/remove' => ['WishlistApiController', 'remove'],
        '/api/scout/request/delete' => ['ScoutApiController', 'delete'],
        '/api/comments/delete' => ['CommentApiController', 'delete'],
        '/api/admin/user/delete' => ['AdminApiController', 'deleteUser'],
    ],
    'GET_API' => [
        '/api/posts/search' => ['PostController', 'searchJson'],
        '/api/posts/filter' => ['PostController', 'filterJson'],
    ],
];
